# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Tomcat-deploy

on: [push]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: '1.8'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Id
      run: echo ${{ secrets.ANSIBLE_VAULT_PASSWORD }} > vault_key
    - name: View Key
      run:  cat vault_key
    - name: Ansible-Vault
      run: ansible-vault view --vault-password-file vault_key tomcat_u_p.yml
    - name: Ansible Playbook Main
      run: ansible-playbook -i /home/ubuntu/ansible_deploy_tomcat main.yml --vault-password-file vault_key
    #- name: Deploy to tomcat
     # run: curl -v -u manager:pass -T /home/runner/work/tomcat_java_maven/tomcat_java_maven/target/WebApp-pipeline.war 'http://65.0.176.198:8080//manager/text/deploy?path=/web_aapp&update=true'
